repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args:
          - --profile
          - black
          - --filter-files

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - --line-length=100
          - --fast

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: no-commit-to-branch
        args:
          - --branch=main

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --config=tox.ini
          - --ignore=F401,E501
        language_version: python3

  - repo: https://github.com/myint/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - --follow-imports=skip
          - --ignore-missing-imports
          - --show-column-numbers
          - --no-pretty


